config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'

  get 'users/new'

  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'  
  match '/help', to: 'static_pages#help', via: 'get'  
  match '/about', to: 'static_pages#about', via: 'get' 

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates(:name, presence: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
	Nikita Belski
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", '#' %></li>
			<li>News</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
    <div class="navbar-inner">
     <div class="container">
       <%= link_to "sample app", root_path, id: "logo" %>
       <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
     </div> 
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="bower_components/html5shiv/dist/html5shiv.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Страница | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

  <h1>О нас</h1>
  <p>Всякая инфа бла бла
	<a href="https://rubygems.org"> Например бла фыыфыыфыфвфвывфыфв</a> 
 Еще бла бла
  </p>
</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

  <h1>Помощь</h1>
  <p>Всякая инфа бла бла
	<a href="https://rubygems.org"> Че то написано</a> 
 Еще бла бла 
  </p>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Главная Страница</h1>
  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>
  <%= link_to "Войти в систему", signup_path, class: "btn btn-large btn-primary" %>
  </div>
  <%= link_to image_tag("logo3.jpeg", alt:"railspng"), 'https://rubygems.org/' %>
  

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>